version: "3.8"
# Compose file build variables set in .env
services:
  supervisor:
    platform: linux/amd64
    build:
      context: ./build
      args:
        PYTHON_VERSION: ${PYTHON_VERSION:-3.11}
        PYTORCH_VERSION: ${PYTORCH_VERSION:-2.3.0}
        COMFYUI_SHA: ${COMFYUI_SHA:-}
        # Base on Python image which is base + python + jupyter
        IMAGE_BASE: ${IMAGE_BASE:-ghcr.io/ai-dock/python:${PYTHON_VERSION:-3.10}-v2-cuda-12.1.1-base-22.04}
      tags:
        - "${COMPOSE_PROJECT_NAME:-ghcr.io/ai-dock/comfyui}:${IMAGE_TAG:-pytorch-${PYTORCH_VERSION:-2.3.0}-py3.10-cuda-12.1.1-base-22.04}"
        
    image: ghcr.io/ai-dock/comfyui:${IMAGE_TAG:-pytorch-${PYTORCH_VERSION:-2.3.0}-py3.10-cuda-12.1.1-base-22.04}
    
    ## For Nvidia GPU's - You probably want to uncomment this
    deploy:
     resources:
       reservations:
         devices:
           - driver: nvidia
             count: all
             capabilities: [gpu]
    
    devices:
      - "/dev/dri:/dev/dri"
      ## For AMD GPU
      #- "/dev/kfd:/dev/kfd"
      
              
    volumes:
      ## Workspace
      - ./workspace:${WORKSPACE:-/workspace/}:rshared
      # You can share /workspace/storage with other non-ComfyUI containers. See README
      #- /path/to/common_storage:${WORKSPACE:-/workspace/}storage/:rshared
      
      # Will echo to root-owned authorized_keys file;
      # Avoids changing local file owner
      - ./config/authorized_keys:/root/.ssh/authorized_keys_mount
      - ./config/provisioning/default.sh:/opt/ai-dock/bin/provisioning.sh
      # In-container development
      - ./build/COPY_ROOT_1/opt/ai-dock/api-wrapper:/opt/ai-dock/api-wrapper

      # Config for ComfyUI Plugin Checkpoints
      - ./config/provisioning/config.json:/opt/ai-dock/bin/build/layer0/config.json

      # Extra nodes for ComfyUI
      - ./extra_nodes/:/opt/ai-dock/bin/extra_nodes/:ro

      # Mount models (optional)
      - ${MODEL_BASE_PATH}/Stable-diffusion:/opt/storage/stable_diffusion/models/ckpt:ro
      - ${MODEL_BASE_PATH}/CLIP:/opt/storage/stable_diffusion/models/clip:ro
      - ${MODEL_BASE_PATH}/clip_vision:/opt/storage/stable_diffusion/models/clip_vision:ro
      - ${MODEL_BASE_PATH}/ControlNet:/opt/storage/stable_diffusion/models/controlnet:ro
      - ${MODEL_BASE_PATH}/embeddings:/opt/storage/stable_diffusion/models/embeddings:ro
      - ${MODEL_BASE_PATH}/facerestore_models:/opt/storage/stable_diffusion/models/facerestore:ro
      - ${MODEL_BASE_PATH}/ESRGAN:/opt/storage/stable_diffusion/models/esrgan:ro
      - ${MODEL_BASE_PATH}/Lora:/opt/storage/stable_diffusion/models/lora:ro
      - ${MODEL_BASE_PATH}/unet:/opt/storage/stable_diffusion/models/unet:ro
      - ${MODEL_BASE_PATH}/VAE:/opt/storage/stable_diffusion/models/vae:ro
      - ${MODEL_BASE_PATH}/stablesr:/opt/storage/stable_diffusion/models/stablesr:ro
      - ${MODEL_BASE_PATH}/comfy3dpack:/opt/storage/stable_diffusion/models/comfy3dpack:ro
      - ${MODEL_BASE_PATH}/clip_interrogator:/opt/storage/stable_diffusion/models/clip_interrogator:ro
      - ${MODEL_BASE_PATH}/prompt_generator:/opt/storage/stable_diffusion/models/prompt_generator:ro
      - ${MODEL_BASE_PATH}/ipadapter:/opt/storage/stable_diffusion/models/ipadapter:ro
      - ${MODEL_BASE_PATH}/hypernetworks:/opt/storage/stable_diffusion/models/hypernetworks:ro
      - ${MODEL_BASE_PATH}/lama:/opt/storage/stable_diffusion/models/lama:ro
      - ${MODEL_BASE_PATH}/clipseg:/opt/storage/stable_diffusion/models/clipseg:ro
      - ${MODEL_BASE_PATH}/sams:/opt/storage/stable_diffusion/models/sam:ro
      - ${MODEL_BASE_PATH}/sam2:/opt/storage/stable_diffusion/models/sam2:ro
      - ${MODEL_BASE_PATH}/vae_approx:/opt/storage/stable_diffusion/models/VAE-approx:ro
      - ${MODEL_BASE_PATH}/configs:/opt/storage/stable_diffusion/models/configs:ro
      - ${MODEL_BASE_PATH}/diffusers:/opt/storage/stable_diffusion/models/diffusers:ro
      - ${MODEL_BASE_PATH}/facedetection:/opt/storage/stable_diffusion/models/facedetection:ro
      - ${MODEL_BASE_PATH}/gligen:/opt/storage/stable_diffusion/models/gligen:ro
      - ${MODEL_BASE_PATH}/insightface:/opt/storage/stable_diffusion/models/insightface:ro
      - ${MODEL_BASE_PATH}/mmdets:/opt/storage/stable_diffusion/models/mmdets:ro
      - ${MODEL_BASE_PATH}/onnx:/opt/storage/stable_diffusion/models/onnx:ro
      - ${MODEL_BASE_PATH}/photomaker:/opt/storage/stable_diffusion/models/photomaker:ro
      - ${MODEL_BASE_PATH}/reactor:/opt/storage/stable_diffusion/models/reactor:ro
      - ${MODEL_BASE_PATH}/style_models:/opt/storage/stable_diffusion/models/style_models:ro
      - ${MODEL_BASE_PATH}/ultralytics:/opt/storage/stable_diffusion/models/ultralytics:ro
      - ${MODEL_BASE_PATH}/echo_mimic:/opt/storage/stable_diffusion/models/echo_mimic:ro
      - ${MODEL_BASE_PATH}/hallo:/opt/storage/stable_diffusion/models/hallo:ro
      - ${MODEL_BASE_PATH}/instantid:/opt/storage/stable_diffusion/models/instantid:ro
      - ${MODEL_BASE_PATH}/layer_model:/opt/storage/stable_diffusion/models/layer_model:ro
      - ${MODEL_BASE_PATH}/live_portrait:/opt/storage/stable_diffusion/models/liveportrait:ro
      - ${MODEL_BASE_PATH}/LLM:/opt/storage/stable_diffusion/models/LLM:ro
      - ${MODEL_BASE_PATH}/svd:/opt/storage/stable_diffusion/models/svd:ro
      - ${MODEL_BASE_PATH}/animatediff_models:/opt/storage/stable_diffusion/models/animatediff_models:ro
      - ${MODEL_BASE_PATH}/animatediff_motion_lora:/opt/storage/stable_diffusion/models/animatediff_motion_lora:ro
      - ${MODEL_BASE_PATH}/BiRefNet:/opt/storage/stable_diffusion/models/BiRefNet:ro

    ports:
        # SSH available on host machine port 2222 to avoid conflict. Change to suit
        - ${SSH_PORT_HOST:-2222}:22
        # Caddy port for service portal
        - ${SERVICEPORTAL_PORT_HOST:-1111}:${SERVICEPORTAL_PORT_HOST:-1111}
        # ComfyUI web interface
        - ${COMFYUI_PORT_HOST:-8188}:${COMFYUI_PORT_HOST:-8188}
        # Jupyter server
        - ${JUPYTER_PORT_HOST:-8888}:${JUPYTER_PORT_HOST:-8888}
        # Syncthing
        - ${SYNCTHING_UI_PORT_HOST:-8384}:${SYNCTHING_UI_PORT_HOST:-8384}
        - ${SYNCTHING_TRANSPORT_PORT_HOST:-22999}:${SYNCTHING_TRANSPORT_PORT_HOST:-22999}
   
    environment:
        # Don't enclose values in quotes
        - AUTO_UPDATE=${AUTO_UPDATE:-false}
        - DIRECT_ADDRESS=${DIRECT_ADDRESS:-127.0.0.1}
        - DIRECT_ADDRESS_GET_WAN=${DIRECT_ADDRESS_GET_WAN:-false}
        - WORKSPACE=${WORKSPACE:-/workspace}
        - WORKSPACE_SYNC=${WORKSPACE_SYNC:-false}
        - CF_TUNNEL_TOKEN=${CF_TUNNEL_TOKEN:-}
        - CF_QUICK_TUNNELS=${CF_QUICK_TUNNELS:-false}
        - CIVITAI_TOKEN=${CIVITAI_TOKEN:-}
        - HF_TOKEN=${HF_TOKEN:-}
        - WEB_ENABLE_AUTH=${WEB_ENABLE_AUTH:-true}
        - WEB_ENABLE_HTTPS=${WEB_ENABLE_HTTPS:-true}
        - WEB_USER=${WEB_USER:-user}
        - WEB_PASSWORD=${WEB_PASSWORD:-password}
        - SSH_PORT_HOST=${SSH_PORT_HOST:-2222}
        - SERVICEPORTAL_PORT_HOST=${SERVICEPORTAL_PORT_HOST:-1111}
        - SERVICEPORTAL_METRICS_PORT=${SERVICEPORTAL_METRICS_PORT:-21111}
        - SERVICEPORTAL_URL=${SERVICEPORTAL_URL:-}
        - COMFYUI_FLAGS=${COMFYUI_FLAGS:-}
        - COMFYUI_PORT_HOST=${COMFYUI_PORT_HOST:-8188}
        - COMFYUI_METRICS_PORT=${COMFYUI_METRICS_PORT:-28188}
        - COMFYUI_URL=${COMFYUI_URL:-}
        - JUPYTER_PORT_HOST=${JUPYTER_PORT_HOST:-8888}
        - JUPYTER_METRICS_PORT=${JUPYTER_METRICS_PORT:-28888}
        - JUPYTER_URL=${JUPYTER_URL:-}
        - SERVERLESS=${SERVERLESS:-false}
        - SYNCTHING_UI_PORT_HOST=${SYNCTHING_UI_PORT_HOST:-8384}
        - SYNCTHING_TRANSPORT_PORT_HOST=${SYNCTHING_TRANSPORT_PORT_HOST:-22999}
        - SYNCTHING_URL=${SYNCTHING_URL:-}
        #- PROVISIONING_SCRIPT=${PROVISIONING_SCRIPT-provisioning.sh}
